### ISSUE TITLE
Moves like e2e4?

### ISSUE THREAD

**Issue by 9acca9** [Cqsi/lichs#14]
Hi. I am making a chess board based on a tutorial (which is not 100% finished, you has to create certain solutions) (the truth is that I know little about programming but I am moving forward), once finished I would like to make it work with lichess .
The code of my program is in python (2.7 currently).
"My code" sends the moves like g1f3, e2e4, etc. (currently playing against stockfish)
Would it be possible to implement this type of change in your code?
Greetings and thank you very much.

**Comment by Cqsi** [comment]
@9acca9 
Yes, this called UCI-notation (you specify from where to where you want to move). When I started this project I used UCI-notation so it shouldn't be too hard to implement since I still have the code. 
Depending on what you're going to use my program to, different things are advisable, but I suggest you read the README.md  and CONTRIBUTING.md files found in this project's root (I think). The CONTRIBUTING.md filr has a few links that might help you. For example, if you you use PyChess to "simulate" the board there's a function to convert from UCI to SAN (the more standard chess notation, the one I'm using, e.g. Nf3) and vice versa.
I don't know if I have time atm to add an UCI-option to Lichs, since that would mean I would have rework a lot of the program, but it's definately possible. 
I can definately (and maybe even want xD) to help if you have any questions, but then be more specific how you're going to use Lichs and how you're making your program.

Cheers

**Comment by 9acca9** [comment]
Ok! thanks for your time. 
when I get ahead a bit, and then research, see and test ... I will communicate with more specific questions (or so I will try :-))
This is the chess I am doing (http://chess.fortherapy.co.uk/home/a-wooden-chess-computer/design-ideas-for-easy-to-build-beaglebone-black-chess-computer/).
And this is part of the code:
http://chess.fortherapy.co.uk/files/2013/07/TestPython-Stockfish.zip (this run on windows but, if you change stockfish 64.exe by just stockfish then run on linux.....

http://chess.fortherapy.co.uk/home/a-wooden-chess-computer/software/python-program-that-runs-stockfish/

Thanks again for your answer!

**Comment by 9acca9** [comment]
Hi.
sorry my stupid question. (still not specific...)

I almost finished my project so im start to look to here...

I want to run your program, and make some changes, so i made a copy of all your code... same name, everything... but...
i can run nothing. 

It tell me 

`  File "c:\Users\xxxxx\Desktop\Proyecto de ajedrez\lichs-master\lichs\__main__.py", line 7, in <module>
    from lichs.Game import Game
ModuleNotFoundError: No module named 'lichs.Game'`

Thanks.

**Comment by 9acca9** [comment]
Hi
Here im. 
In your code the lichess moves are reciving in this way (i think.....):
https://github.com/Cqsi/lichs/blob/master/lichs/Game.py#L47

Can you tell me if instead of getting that kind of move, can i get a e2-e4 (i prefer this) or Nf3? or if there is some part in your code where i can get that kind of info. Maybe some function that can change that kind (Forsyth-Edwards Notation strings), i think to e2-e4...

Thanks.

(im trying to maybe do just a little change to your code, to mix with "mine".)
